// 기본 표정 레시피: 기본 태그 + 자연어 묘사 + 시선·각도 조합
// 자연어를 잘 알아듣는 모델(예: Tsubaki.3)에서 감정이 더 살아난다.
const PRESET_GROUPS = [
  '웃음', '도발·오만', '분노', '슬픔', '당황·부끄러움', '놀람',
  '냉담·무표정', '피곤·나른', '진지·긴장', '광기', '설렘·애정', '섹시·분위기', '배경', '자연', '색감', '기타',
];

const DEFAULT_PRESETS = [
  // 웃음
  { g: '웃음', name: '환하게 웃는 얼굴', desc: '눈까지 웃는 밝은 웃음 + 홍조',
    text: 'smile, open mouth, :d, blush, happy, bright genuine smile reaching his eyes, eyes slightly narrowed from laughing' },
  { g: '웃음', name: '부드러운 미소', desc: '입 다문 잔잔한 미소',
    text: 'light smile, closed mouth, gentle expression, soft eyes, warm gaze, relaxed eyebrows' },
  { g: '웃음', name: '수줍은 미소', desc: '시선 피하며 살짝 웃음',
    text: 'light smile, blush, looking away, embarrassed, shy smile, lowering his gaze, hand partially covering his mouth' },
  { g: '웃음', name: '장난스러운 웃음', desc: '윙크 + 혀 + 갸웃',
    text: 'grin, one eye closed, tongue out, head tilt, playful expression, mischievous smile' },
  { g: '웃음', name: '폭소', desc: '고개 젖히고 크게 웃음',
    text: 'laughing, open mouth, closed eyes, tears, head thrown back in laughter, hand on own stomach' },
  { g: '웃음', name: '씁쓸한 미소', desc: '곤란한 눈썹 + 슬픈 웃음',
    text: 'light smile, troubled eyebrows, sad smile, bittersweet expression, eyes cast down' },
  { g: '웃음', name: '다정하게 내려다봄', desc: '아래에서 올려다본 구도, 부드러운 눈빛',
    text: 'light smile, half-closed eyes, looking at viewer, from below, tender expression, looking down at the viewer affectionately' },

  // 도발·오만
  { g: '도발·오만', name: '깔보는 비웃음', desc: '턱 들고 한쪽 입꼬리만 올림',
    text: 'smirk, half-closed eyes, condescending gaze, from below, one corner of his mouth raised, chin slightly lifted, looking down at the viewer' },
  { g: '도발·오만', name: '여유로운 도발', desc: '게슴츠레한 눈 + 턱 괴기',
    text: 'smirk, jitome, head tilt, hand on own chin, confident expression, amused gaze, teasing look' },
  { g: '도발·오만', name: '지배적인 시선', desc: '무표정으로 위에서 내려다봄',
    text: 'expressionless, narrowed eyes, looking at viewer, from below, dominant, cold stare looking down at the viewer, chin up' },
  { g: '도발·오만', name: '악역 미소', desc: '얼굴 반쯤 그림자 + 빛나는 눈',
    text: 'evil smile, shaded face, glowing eyes, narrowed eyes, sinister grin, half of his face in shadow' },
  { g: '도발·오만', name: '안경 너머 한심한 눈빛', desc: '안경 내리고 위로 쳐다봄',
    text: 'glasses, looking over eyewear, jitome, raised eyebrow, unimpressed expression, peering over his glasses' },

  // 분노
  { g: '분노', name: '버럭 화냄', desc: '소리치는 얼굴 + 핏줄',
    text: 'angry, v-shaped eyebrows, open mouth, clenched teeth, veins, shouting, furious expression' },
  { g: '분노', name: '짜증에 머리 헝클', desc: '머리 쥐어뜯으며 내려다봄',
    text: 'angry, v-shaped eyebrows, parted lips, glaring, hand in own hair, messy hair, from below, gripping his own hair in frustration, looking down' },
  { g: '분노', name: '조용한 분노', desc: '무표정인데 눈이 차갑게 가라앉음',
    text: 'angry, expressionless, glaring, shaded face, narrowed eyes, suppressed rage, jaw clenched, cold eyes' },
  { g: '분노', name: '째려봄', desc: '옆눈질로 짜증',
    text: 'annoyed, glaring, jitome, frown, furrowed brow, looking at viewer, side glance' },
  { g: '분노', name: '이 악물고 참음', desc: '떨릴 만큼 참는 얼굴',
    text: 'angry, clenched teeth, furrowed brow, sweat, trembling with anger, holding back his rage' },

  // 슬픔
  { g: '슬픔', name: '눈물 글썽', desc: '참으려는데 차오름',
    text: 'sad, tearing up, troubled eyebrows, parted lips, glistening eyes, holding back tears' },
  { g: '슬픔', name: '소리 없이 눈물', desc: '무표정에 눈물 한 줄기',
    text: 'crying, tears, expressionless, closed mouth, empty eyes, a single tear rolling down his cheek' },
  { g: '슬픔', name: '오열', desc: '얼굴 감싸고 흐느낌',
    text: 'crying, tears, open mouth, troubled eyebrows, sobbing, hand covering his face' },
  { g: '슬픔', name: '공허함', desc: '고개 떨군 텅 빈 눈',
    text: 'empty eyes, expressionless, looking down, hollow gaze, head hanging low, exhausted' },

  // 당황·부끄러움
  { g: '당황·부끄러움', name: '얼굴 새빨개짐', desc: '눈 커지고 허둥댐',
    text: 'blush, embarrassed, wide-eyed, open mouth, sweatdrop, flustered, face turning bright red' },
  { g: '당황·부끄러움', name: '부끄러워 입 가림', desc: '손등으로 입 가리고 시선 회피',
    text: 'blush, covering mouth, looking away, embarrassed, avoiding eye contact, back of his hand over his mouth' },
  { g: '당황·부끄러움', name: '츤데레 삐짐', desc: '팔짱 끼고 고개 홱',
    text: 'blush, pout, looking away, annoyed, crossed arms, turning his face away' },
  { g: '당황·부끄러움', name: '난처한 웃음', desc: '볼 긁으며 어색하게',
    text: 'nervous, sweatdrop, troubled eyebrows, light smile, awkward smile, scratching his cheek' },

  // 놀람
  { g: '놀람', name: '깜짝 놀람', desc: '동공 수축 + 입 벌림',
    text: 'surprised, wide-eyed, open mouth, :o, constricted pupils, startled' },
  { g: '놀람', name: '어리둥절', desc: '갸웃하며 멍한 얼굴',
    text: 'confused, head tilt, parted lips, blank stare, puzzled expression' },

  // 냉담·무표정
  { g: '냉담·무표정', name: '무심한 얼굴', desc: '관심 없는 듯 시선 돌림',
    text: 'expressionless, half-closed eyes, bored, closed mouth, looking away, indifferent gaze' },
  { g: '냉담·무표정', name: '차가운 시선', desc: '감정 없이 똑바로 봄',
    text: 'expressionless, narrowed eyes, looking at viewer, cold eyes, sharp gaze, emotionless face' },
  { g: '냉담·무표정', name: '한숨', desc: '이마 짚고 질린 얼굴',
    text: 'sigh, closed eyes, tired, annoyed, hand on own forehead, exhaling in exasperation' },

  // 피곤·나른
  { g: '피곤·나른', name: '졸린 얼굴', desc: '하품 + 눈 비빔',
    text: 'sleepy, half-closed eyes, yawning, messy hair, drowsy expression, rubbing his eye' },
  { g: '피곤·나른', name: '지친 얼굴', desc: '다크서클 + 넥타이 풀림',
    text: 'tired, bags under eyes, half-closed eyes, sweat, loose necktie, exhausted after a long day' },
  { g: '피곤·나른', name: '나른한 매력', desc: '반쯤 뜬 눈 + 기대앉음',
    text: 'half-closed eyes, light smile, parted lips, leaning back, relaxed, languid gaze' },

  // 진지·긴장
  { g: '진지·긴장', name: '결연함', desc: '정면을 강하게 응시',
    text: 'serious, v-shaped eyebrows, closed mouth, looking at viewer, determined expression, intense gaze' },
  { g: '진지·긴장', name: '집중', desc: '아래를 보며 몰두',
    text: 'serious, narrowed eyes, looking down, focused expression, concentrating' },
  { g: '진지·긴장', name: '긴장', desc: '식은땀 + 침 삼킴',
    text: 'nervous, sweat, clenched teeth, troubled eyebrows, anxious expression, swallowing hard' },

  // 광기
  { g: '광기', name: '광기 어린 미소', desc: '동공 수축 + 갸웃',
    text: 'crazy smile, constricted pupils, shaded face, wide-eyed, head tilt, unhinged grin' },
  { g: '광기', name: '집착하는 시선', desc: '텅 빈 눈으로 미소',
    text: 'empty eyes, light smile, head tilt, looking at viewer, shaded face, obsessive gaze' },

  // 설렘·애정
  { g: '설렘·애정', name: '설레는 얼굴', desc: '홍조 + 살짝 벌린 입',
    text: 'blush, light smile, wide-eyed, parted lips, looking at another, flustered, heart pounding' },
  { g: '설렘·애정', name: '애틋한 눈빛', desc: '곤란한 눈썹 + 그리운 눈',
    text: 'troubled eyebrows, light smile, blush, looking at another, longing gaze, tender expression' },

  // 색감 (톤다운)
  { g: '색감', name: '차분한 톤다운', desc: '채도 낮춤 기본형',
    text: '(muted color:1.2), desaturated colors, muted tones, low saturation, subdued color palette' },
  { g: '색감', name: '누아르 무채색', desc: '차가운 회색 톤 + 강한 명암',
    text: 'noir, muted color, high contrast, deep shadows, desaturated cinematic color grading, cold grey tones' },
  { g: '색감', name: '빈티지 필름', desc: '바랜 색 + 필름 질감',
    text: 'film grain, muted color, faded colors, vintage film photography look, soft warm tint' },
  { g: '색감', name: '흑백 + 포인트 컬러', desc: '한 색만 남기기 (red를 원하는 색으로)',
    text: 'monochrome, spot color, black and white image with a single red accent' },
  { g: '색감', name: '파스텔 톤', desc: '연하고 부드러운 색',
    text: 'pale color, pastel colors, soft light, airy and gentle color palette' },
  // 색감 (비비드·청량)
  { g: '색감', name: '쨍한 비비드', desc: '채도·대비 높게',
    text: '(vivid colors:1.2), colorful, saturated, high contrast, bold vibrant color palette' },
  { g: '색감', name: '청량한 여름', desc: '파란 하늘 + 햇살 + 청록',
    text: 'summer, blue sky, sunlight, light rays, aqua theme, crisp cool tones, fresh and clear color palette, refreshing atmosphere' },
  { g: '색감', name: '투명한 청량감', desc: '밝고 맑은 블루·화이트',
    text: 'cool color palette, white theme, soft light, translucent clear colors, light blue and white tones, clean airy atmosphere' },
  { g: '색감', name: '네온 시티팝', desc: '밤거리 + 마젠타·시안',
    text: 'night, city lights, neon lights, vivid colors, synthwave-inspired color palette, magenta and cyan glow' },
  { g: '색감', name: '따뜻한 노을', desc: '골든아워 역광',
    text: 'sunset, backlighting, warm color palette, golden hour lighting, orange and pink tones' },
  // 색감 (네거티브 칸용)
  { g: '색감', name: '[네거티브] 채도 낮추기', desc: '네거티브 칸에 넣으면 톤다운',
    text: 'vivid colors, oversaturated, colorful, saturated' },
  { g: '색감', name: '[네거티브] 색 빠짐 방지', desc: '네거티브 칸에 넣으면 비비드 유지',
    text: 'monochrome, greyscale, desaturated, muted color, dull colors' },

  // 배경 (장면 레시피)
  { g: '배경', name: '저택 거실', desc: '샹들리에 + 벽난로 + 가죽 소파',
    text: 'indoors, mansion, living room, luxurious, chandelier, fireplace, leather couch, coffee table, rug, tall windows with heavy velvet curtains, warm dim lighting, detailed background' },
  { g: '배경', name: '저택 복도', desc: '대리석 바닥 + 걸린 그림',
    text: 'indoors, mansion, hallway, marble floor, chandelier, painting (object), long corridor lined with portraits, grand staircase in the distance, detailed background' },
  { g: '배경', name: '무도회장', desc: '금장식 + 대리석 기둥',
    text: 'indoors, ballroom, chandelier, marble floor, pillar, luxurious, golden ornate decorations, grand hall, detailed background' },
  { g: '배경', name: '서재', desc: '책장 + 스탠드 + 안락의자',
    text: 'indoors, study, bookshelf, desk, desk lamp, armchair, book stack, wooden wall, warm lamplight, cozy atmosphere, detailed background' },
  { g: '배경', name: '창가 아침 햇살', desc: '얇은 커튼이 바람에 날림',
    text: 'indoors, window, sheer curtains, curtains blowing in the wind, sunlight, light rays, morning light streaming through the window, soft shadows' },
  { g: '배경', name: '비 오는 밤 창가', desc: '빗방울 유리 너머 도시 불빛',
    text: 'indoors, night, window, rain, dim lighting, raindrops on the window glass, blurred city lights outside, reflection on the glass' },
  { g: '배경', name: '호텔 스위트 야경', desc: '통창 너머 밤 도시',
    text: 'indoors, hotel room, night, large window, city lights, bed, floor-to-ceiling windows overlooking the night city, modern luxury interior' },
  { g: '배경', name: '침실 (아늑)', desc: '구겨진 시트 + 스탠드',
    text: 'indoors, bedroom, bed, pillow, blanket, lamp, cozy, warm lighting, rumpled sheets, soft morning light' },
  { g: '배경', name: '바 카운터', desc: '호박색 조명 + 술병',
    text: 'indoors, bar (place), counter, bar stool, wine bottle, wine glass, dim lighting, warm amber lights, shelves of liquor bottles, moody atmosphere' },
  { g: '배경', name: '야근 사무실', desc: '스탠드 하나만 켜진 밤',
    text: 'indoors, office, desk, computer, night, window, city lights, desk lamp, empty office late at night, only the desk lamp lit' },
  { g: '배경', name: '카페 창가', desc: '햇살 + 화분 + 커피',
    text: 'indoors, cafe, table, mug, window, sunlight, potted plant, cozy cafe interior, latte on the table' },
  { g: '배경', name: '방과후 교실', desc: '빈 교실 + 노을빛',
    text: 'indoors, classroom, desk, chair, window, sunset, empty classroom after school, orange light through the windows' },
  { g: '배경', name: '온실', desc: '유리 천장 + 초록 식물',
    text: 'indoors, greenhouse, plant, flower, sunlight, dappled sunlight, glass roof, lush green plants' },
  { g: '배경', name: '고딕 성당', desc: '스테인드글라스 빛 + 촛불',
    text: 'indoors, church, stained glass, pillar, candle, light rays, gothic architecture, colorful light pouring through stained glass windows' },
  { g: '배경', name: '옥상 노을', desc: '난간 + 도시 스카이라인',
    text: 'outdoors, rooftop, railing, sunset, cityscape, wind, orange sky over the city skyline' },
  { g: '배경', name: '비 오는 네온 골목', desc: '젖은 바닥에 네온 반사',
    text: 'outdoors, alley, night, rain, neon lights, wet pavement reflecting neon lights, puddles' },

  // 자연 (장면 레시피)
  { g: '자연', name: '햇살 드는 숲', desc: '나뭇잎 사이로 빛줄기',
    text: 'outdoors, forest, tree, foliage, moss, dappled sunlight, light rays, sunbeams filtering through the leaves, lush green atmosphere' },
  { g: '자연', name: '비 내리는 숲길', desc: '안개 + 젖은 잎',
    text: 'outdoors, forest, rain, fog, tree, wet leaves glistening, narrow forest path, misty atmosphere' },
  { g: '자연', name: '대나무 숲', desc: '높이 솟은 대나무 + 빛줄기',
    text: 'outdoors, bamboo forest, bamboo, light rays, tall bamboo stalks towering overhead, quiet path' },
  { g: '자연', name: '벚꽃길', desc: '흩날리는 꽃잎',
    text: 'outdoors, spring (season), cherry blossoms, tree, falling petals, path lined with blooming cherry trees, soft pink atmosphere' },
  { g: '자연', name: '단풍 공원', desc: '떨어지는 낙엽 + 황금빛',
    text: 'outdoors, autumn, autumn leaves, maple leaf, falling leaves, tree, park bench, warm golden foliage' },
  { g: '자연', name: '여름 바다', desc: '파란 하늘 + 뭉게구름 + 파도',
    text: 'outdoors, summer, beach, ocean, waves, sand, blue sky, cumulonimbus cloud, horizon, sparkling sea' },
  { g: '자연', name: '노을 해변', desc: '바다에 비친 주황 하늘',
    text: 'outdoors, beach, sunset, ocean, horizon, reflection, orange sky, orange sky mirrored on the calm sea' },
  { g: '자연', name: '달빛 밤바다', desc: '어두운 파도 위 은빛 달빛',
    text: 'outdoors, night, ocean, waves, moon, moonlight, reflection, silver moonlight shimmering on dark waves' },
  { g: '자연', name: '안개 낀 호숫가', desc: '산이 비치는 잔잔한 호수',
    text: 'outdoors, lake, reflection, mountain, tree, fog, calm water, mist hovering over the lake' },
  { g: '자연', name: '폭포', desc: '이끼 낀 바위 + 물보라',
    text: 'outdoors, waterfall, rock, moss, river, splashing, water spray, lush greenery' },
  { g: '자연', name: '바람 부는 초원', desc: '끝없는 풀밭 + 흘러가는 구름',
    text: 'outdoors, meadow, tall grass, wind, blue sky, cloud, grass swaying in the wind, vast open field' },
  { g: '자연', name: '해바라기밭', desc: '한여름 햇살',
    text: 'outdoors, summer, sunflower, flower field, blue sky, sunlight, cumulonimbus cloud' },
  { g: '자연', name: '눈 덮인 숲', desc: '조용히 내리는 눈',
    text: 'outdoors, winter, snow, snowing, snowflakes, pine tree, snow-covered forest, quiet snowfall' },
  { g: '자연', name: '별이 쏟아지는 밤', desc: '은하수 + 별똥별 + 언덕',
    text: 'outdoors, night, starry sky, milky way, shooting star, hill, grass, vast sky full of stars' },
  { g: '자연', name: '반딧불 여름밤', desc: '풀숲 위를 떠다니는 빛',
    text: 'outdoors, night, summer, fireflies, tall grass, forest, glowing fireflies drifting in the dark' },
  { g: '자연', name: '바닷속', desc: '수면에서 내려오는 빛',
    text: 'underwater, water, bubble, fish, light rays, sunlight filtering down from the surface' },
  { g: '자연', name: '폭풍 치는 절벽', desc: '먹구름 + 거센 파도',
    text: 'outdoors, cliff, ocean, waves, storm, overcast, wind, dramatic sky, waves crashing against the rocks' },

  // 섹시·분위기 (노골적이지 않은 선)
  { g: '섹시·분위기', name: '풀어헤친 셔츠', desc: '단추 풀고 넥타이 느슨하게',
    text: 'open shirt, partially unbuttoned, collarbone, loose necktie, sweat, messy hair, half-closed eyes, disheveled look after a long night' },
  { g: '섹시·분위기', name: '넥타이 푸는 순간', desc: '한 손으로 넥타이 당기며 씩',
    text: 'adjusting necktie, smirk, half-closed eyes, looking at viewer, loosening his necktie with one hand' },
  { g: '섹시·분위기', name: '젖은 셔츠', desc: '비에 젖어 달라붙은 셔츠',
    text: 'wet shirt, see-through shirt, wet hair, water drop, rain, dripping wet, fabric clinging to his body' },
  { g: '섹시·분위기', name: '샤워 후', desc: '젖은 머리 + 목에 건 수건',
    text: 'after bathing, wet hair, towel around neck, shirtless, steam, water drop, relaxed expression' },
  { g: '섹시·분위기', name: '운동 후', desc: '땀 + 핏줄 + 거친 숨',
    text: 'sweat, tank top, toned male, veins, heavy breathing, towel around neck, flushed after a workout' },
  { g: '섹시·분위기', name: '요염한 눈빛', desc: '나른한 눈 + 살짝 벌린 입',
    text: 'bedroom eyes, half-closed eyes, seductive smile, parted lips, light blush, looking at viewer, smoldering gaze' },
  { g: '섹시·분위기', name: '도발하는 손짓', desc: '오라는 손짓 + 씩 웃음',
    text: 'come hither, smirk, head tilt, looking at viewer, beckoning with one finger, teasing invitation' },
  { g: '섹시·분위기', name: '침대 위 나른한 아침', desc: '헝클어진 머리 + 햇살',
    text: 'on bed, lying, bed sheet, shirtless, messy hair, half-closed eyes, sunlight through window, lazy morning' },
  { g: '섹시·분위기', name: '벽쿵 도발', desc: '가까이 몰아붙이며 씩',
    text: 'kabedon, smirk, face-to-face, looking at another, leaning in close, intense gaze' },
  { g: '섹시·분위기', name: '귓속말', desc: '귀에 대고 속삭임',
    text: 'whispering, light smile, half-closed eyes, blush, leaning in close to his ear' },
];
